version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vaultdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
